name: coguide-zarr
channels:
  - conda-forge
dependencies:
  - python=3.11
  - adlfs
  - aiohttp
  - dask
  - fsspec
  - ipykernel
  - jupyterlab
  - planetary-computer
  - pystac
  - requests
  - rich
  - xarray
  - zarr
